import { NextResponse } from 'next/server'
import { getAdminClient } from '@/lib/supabase/admin'

export const dynamic = 'force-dynamic'

export async function POST() {
  const supabase = getAdminClient()

  const future = (days: number) => new Date(Date.now() + days * 86400000).toISOString()

  const items = [
    {
      title: 'MacBook Air M1 13" — excellent condition',
      description: 'Barely used MacBook Air M1, 8GB RAM, 256GB SSD. Bought at the start of Erasmus, selling because I\'m going back home. Comes with original charger and box.',
      category: 'electronics',
      condition: 'very_good',
      price: 750,
      is_free: false,
      is_negotiable: true,
      brand: 'Apple',
      color: 'Space Grey',
      photos: ['https://images.unsplash.com/photo-1611186871525-3c605bcef954?w=600&q=80'],
      seller_name: 'Lukas',
      seller_nationality: '🇩🇪 German',
      university: 'UPV',
      neighborhood: 'Ruzafa',
      contact_whatsapp: '+34 612 345 678',
      contact_email: null,
      location: 'Valencia',
      status: 'active',
      expires_at: future(60),
    },
    {
      title: 'iPhone 13 128GB — good condition',
      description: 'iPhone 13, midnight black, 128GB. Screen is perfect, small scratch on the back. Selling as I upgraded. Unlocked, works with any SIM.',
      category: 'electronics',
      condition: 'good',
      price: 420,
      is_free: false,
      is_negotiable: true,
      brand: 'Apple',
      color: 'Midnight',
      photos: ['https://images.unsplash.com/photo-1592750475338-74b7b21085ab?w=600&q=80'],
      seller_name: 'Sofia',
      seller_nationality: '🇮🇹 Italian',
      university: 'UV',
      neighborhood: 'El Carmen',
      contact_whatsapp: '+34 623 456 789',
      contact_email: 'sofia@example.com',
      location: 'Valencia',
      status: 'active',
      expires_at: future(45),
    },
    {
      title: 'Sony WH-1000XM4 Noise Cancelling Headphones',
      description: 'Premium noise-cancelling headphones, barely used. Perfect for studying in cafes. Comes with original case and cables.',
      category: 'electronics',
      condition: 'very_good',
      price: 180,
      is_free: false,
      is_negotiable: false,
      brand: 'Sony',
      color: 'Black',
      photos: ['https://images.unsplash.com/photo-1505740420928-5e560c06d30e?w=600&q=80'],
      seller_name: 'Marta',
      seller_nationality: '🇵🇱 Polish',
      university: 'UPV',
      neighborhood: 'Benimaclet',
      contact_whatsapp: '+34 634 567 890',
      contact_email: null,
      location: 'Valencia',
      status: 'active',
      expires_at: future(50),
    },
    {
      title: 'Women\'s Zara summer dress — size S',
      description: 'Beautiful floral dress from Zara, worn twice. Perfect for Valencia\'s warm weather. Size S, fits true to size.',
      category: 'clothes_women',
      condition: 'new_without_tags',
      price: 18,
      is_free: false,
      is_negotiable: false,
      brand: 'Zara',
      color: 'Floral',
      size_clothes: 'S',
      photos: ['https://images.unsplash.com/photo-1572804013309-59a88b7e92f1?w=600&q=80'],
      seller_name: 'Camille',
      seller_nationality: '🇫🇷 French',
      university: 'UV',
      neighborhood: 'Gran Vía',
      contact_whatsapp: '+34 645 678 901',
      contact_email: null,
      location: 'Valencia',
      status: 'active',
      expires_at: future(30),
    },
    {
      title: 'Men\'s H&M hoodie — size M',
      description: 'Grey hoodie from H&M, worn a few times. Very comfortable for cooler evenings. Size M.',
      category: 'clothes_men',
      condition: 'good',
      price: 12,
      is_free: false,
      is_negotiable: true,
      brand: 'H&M',
      color: 'Grey',
      size_clothes: 'M',
      photos: ['https://images.unsplash.com/photo-1556821840-3a63f15732ce?w=600&q=80'],
      seller_name: 'Jan',
      seller_nationality: '🇳🇱 Dutch',
      university: 'UPV',
      neighborhood: 'Ruzafa',
      contact_whatsapp: '+34 656 789 012',
      contact_email: null,
      location: 'Valencia',
      status: 'active',
      expires_at: future(40),
    },
    {
      title: 'Nike Air Force 1 white — size 42',
      description: 'Classic white Nike Air Force 1, size 42 (EU). Worn a handful of times, still in great shape. Light sole marks but no visible damage.',
      category: 'shoes_men',
      condition: 'very_good',
      price: 55,
      is_free: false,
      is_negotiable: true,
      brand: 'Nike',
      color: 'White',
      size_shoes: '42',
      photos: ['https://images.unsplash.com/photo-1600269452121-4f2416e55c28?w=600&q=80'],
      seller_name: 'Rafael',
      seller_nationality: '🇧🇷 Brazilian',
      university: 'CEU',
      neighborhood: 'Ensanche',
      contact_whatsapp: '+34 667 890 123',
      contact_email: null,
      location: 'Valencia',
      status: 'active',
      expires_at: future(35),
    },
    {
      title: 'IKEA desk + chair set',
      description: 'IKEA Micke desk (105x50cm) + Alefjäll swivel chair. Both in good condition. Perfect for studying. Must collect — I\'m in Benimaclet.',
      category: 'furniture',
      condition: 'good',
      price: 65,
      is_free: false,
      is_negotiable: true,
      brand: 'IKEA',
      color: 'White/Black',
      photos: ['https://images.unsplash.com/photo-1593642632559-0c6d3fc62b89?w=600&q=80'],
      seller_name: 'Anna',
      seller_nationality: '🇩🇪 German',
      university: 'UV',
      neighborhood: 'Benimaclet',
      contact_whatsapp: '+34 678 901 234',
      contact_email: 'anna@example.com',
      location: 'Valencia',
      status: 'active',
      expires_at: future(55),
    },
    {
      title: 'Spanish & Business Law textbooks (pack of 4)',
      description: 'Bundle of 4 textbooks: Spanish Grammar B2, Business Law 101, Marketing Fundamentals, and European Economics. All in good condition with some highlights.',
      category: 'books_studies',
      condition: 'good',
      price: 30,
      is_free: false,
      is_negotiable: true,
      brand: null,
      color: null,
      photos: ['https://images.unsplash.com/photo-1544716278-ca5e3f4abd8c?w=600&q=80'],
      seller_name: 'Katarzyna',
      seller_nationality: '🇵🇱 Polish',
      university: 'UPV',
      neighborhood: 'Cabanyal',
      contact_whatsapp: '+34 689 012 345',
      contact_email: null,
      location: 'Valencia',
      status: 'active',
      expires_at: future(45),
    },
    {
      title: 'Mountain bike — barely used',
      description: 'Quality mountain bike, 26" wheels, 21 speeds. Only used a few times to explore Valencia. Selling because I\'m leaving. Helmet included!',
      category: 'bikes_transport',
      condition: 'very_good',
      price: 120,
      is_free: false,
      is_negotiable: true,
      brand: 'BH',
      color: 'Blue',
      photos: ['https://images.unsplash.com/photo-1485965120184-e220f721d03e?w=600&q=80'],
      seller_name: 'Pedro',
      seller_nationality: '🇵🇹 Portuguese',
      university: 'UV',
      neighborhood: 'Malvarrosa',
      contact_whatsapp: '+34 690 123 456',
      contact_email: null,
      location: 'Valencia',
      status: 'active',
      expires_at: future(40),
    },
    {
      title: 'Nespresso coffee machine + 40 pods',
      description: 'Nespresso Essenza Mini, black. Works perfectly. Comes with 40 mixed pods. Leaving Valencia and can\'t take it with me.',
      category: 'kitchen_home',
      condition: 'very_good',
      price: 45,
      is_free: false,
      is_negotiable: false,
      brand: 'Nespresso',
      color: 'Black',
      photos: ['https://images.unsplash.com/photo-1495474472287-4d71bcdd2085?w=600&q=80'],
      seller_name: 'Elena',
      seller_nationality: '🇷🇴 Romanian',
      university: 'UV',
      neighborhood: 'Ruzafa',
      contact_whatsapp: '+34 601 234 567',
      contact_email: null,
      location: 'Valencia',
      status: 'active',
      expires_at: future(30),
    },
    {
      title: 'Yoga mat + resistance bands — FREE',
      description: 'Thick non-slip yoga mat (6mm) + set of 3 resistance bands. Used a few times. Free to a good home — just come collect in Mestalla.',
      category: 'sports_outdoors',
      condition: 'very_good',
      price: 0,
      is_free: true,
      is_negotiable: false,
      brand: null,
      color: 'Purple',
      photos: ['https://images.unsplash.com/photo-1544367567-0f2fcb009e0b?w=600&q=80'],
      seller_name: 'Lena',
      seller_nationality: '🇩🇪 German',
      university: 'UPV',
      neighborhood: 'Mestalla',
      contact_whatsapp: '+34 612 345 670',
      contact_email: null,
      location: 'Valencia',
      status: 'active',
      expires_at: future(20),
    },
    {
      title: 'Leather backpack — Fjällräven style',
      description: 'Brown canvas & leather backpack, fits 15" laptop. Very stylish, lots of compartments. Used for one semester.',
      category: 'bags_accessories',
      condition: 'good',
      price: 35,
      is_free: false,
      is_negotiable: false,
      brand: null,
      color: 'Brown',
      photos: ['https://images.unsplash.com/photo-1553062407-98eeb64c6a62?w=600&q=80'],
      seller_name: 'Ingrid',
      seller_nationality: '🇩🇪 German',
      university: 'UV',
      neighborhood: 'El Carmen',
      contact_whatsapp: '+34 623 456 781',
      contact_email: null,
      location: 'Valencia',
      status: 'active',
      expires_at: future(50),
    },
  ]

  const ticketItems = [
    {
      title: '2x Pacha Valencia tickets — Saturday night',
      description: 'Selling 2 tickets for Pacha Valencia this Saturday. Bought them but can\'t go anymore — friends bailed. Face value €25 each, selling as a pair.',
      category: 'tickets_events',
      condition: 'new_with_tags',
      price: 45,
      is_free: false,
      is_negotiable: true,
      brand: null,
      color: null,
      event_date: new Date(Date.now() + 5 * 86400000).toISOString().slice(0, 10),
      event_venue: 'Pacha Valencia, Calle Eugenia Viñes 152',
      ticket_quantity: 2,
      photos: ['https://images.unsplash.com/photo-1566737236500-c8ac43014a67?w=600&q=80'],
      seller_name: 'Marco',
      seller_nationality: '🇮🇹 Italian',
      university: 'UV',
      neighborhood: 'El Carmen',
      contact_whatsapp: '+34 611 111 201',
      contact_email: null,
      location: 'Valencia',
      status: 'active',
      expires_at: future(5),
    },
    {
      title: '1x Rototom Sunsplash festival pass',
      description: 'One full 7-day festival pass for Rototom Sunsplash in Benicàssim. Can\'t attend due to flight change. Original price €180, selling below cost.',
      category: 'tickets_events',
      condition: 'new_with_tags',
      price: 140,
      is_free: false,
      is_negotiable: true,
      brand: null,
      color: null,
      event_date: new Date(Date.now() + 20 * 86400000).toISOString().slice(0, 10),
      event_venue: 'Benicàssim, Castellón',
      ticket_quantity: 1,
      photos: ['https://images.unsplash.com/photo-1533174072545-7a4b6ad7a6c3?w=600&q=80'],
      seller_name: 'Hanna',
      seller_nationality: '🇩🇪 German',
      university: 'UPV',
      neighborhood: 'Ruzafa',
      contact_whatsapp: '+34 611 111 202',
      contact_email: null,
      location: 'Valencia',
      status: 'active',
      expires_at: future(18),
    },
    {
      title: '3x Sala Republica techno night — Friday',
      description: 'Three tickets for Friday\'s techno night at Sala Republica. Great lineup, already paid €15 each. Selling all 3 together.',
      category: 'tickets_events',
      condition: 'new_with_tags',
      price: 40,
      is_free: false,
      is_negotiable: false,
      brand: null,
      color: null,
      event_date: new Date(Date.now() + 3 * 86400000).toISOString().slice(0, 10),
      event_venue: 'Sala Republica, Valencia',
      ticket_quantity: 3,
      photos: ['https://images.unsplash.com/photo-1571266028243-e4733b0f0bb0?w=600&q=80'],
      seller_name: 'Tomasz',
      seller_nationality: '🇵🇱 Polish',
      university: 'CEU',
      neighborhood: 'El Carmen',
      contact_whatsapp: '+34 611 111 203',
      contact_email: null,
      location: 'Valencia',
      status: 'active',
      expires_at: future(3),
    },
    {
      title: '2x Valencia CF vs Villarreal match tickets',
      description: 'Two seats together, Tribuna Sur, row 12. Can\'t make it — work conflict. Face value €45 each.',
      category: 'tickets_events',
      condition: 'new_with_tags',
      price: 80,
      is_free: false,
      is_negotiable: false,
      brand: null,
      color: null,
      event_date: new Date(Date.now() + 10 * 86400000).toISOString().slice(0, 10),
      event_venue: 'Estadio Mestalla, Valencia',
      ticket_quantity: 2,
      photos: ['https://images.unsplash.com/photo-1508098682722-e99c643e7f0b?w=600&q=80'],
      seller_name: 'Carlos',
      seller_nationality: '🇪🇸 Spanish',
      university: 'UV',
      neighborhood: 'Mestalla',
      contact_whatsapp: '+34 611 111 204',
      contact_email: null,
      location: 'Valencia',
      status: 'active',
      expires_at: future(9),
    },
  ]

  // Make idempotent — remove existing seed listings by seller contact
  const seedPhones = [...items, ...ticketItems].map(i => i.contact_whatsapp)
  // eslint-disable-next-line @typescript-eslint/no-explicit-any
  await (supabase as any).from('marketplace_listings').delete().in('contact_whatsapp', seedPhones)

  // eslint-disable-next-line @typescript-eslint/no-explicit-any
  const { error } = await (supabase as any).from('marketplace_listings').insert([...items, ...ticketItems])
  if (error) return NextResponse.json({ error: error.message }, { status: 500 })

  return NextResponse.json({ ok: true, inserted: items.length + ticketItems.length })
}
