import { NextResponse } from 'next/server'
import { getAdminClient } from '@/lib/supabase/admin'

export const dynamic = 'force-dynamic'

export async function POST() {
  const supabase = getAdminClient()

  const now = new Date()
  const d = (days: number) => new Date(now.getTime() + days * 86400000).toISOString()

  // ── 1. Student listings ───────────────────────────────────────

  const listings = [
    {
      type: 'room_available' as const,
      title: 'Bright private room in Ruzafa — bills included',
      description: 'Lovely private room in a modern flat in the heart of Ruzafa. Very bright, has a big window and good storage space. The flat is clean, quiet and well-maintained. Bills (water, electricity, wifi) all included. 2 flatmates — both Erasmus students, very friendly and international.',
      price: 420,
      neighborhood: 'Ruzafa',
      room_type: 'private_room' as const,
      available_from: d(5),
      available_until: d(180),
      flatmates_count: 2,
      flatmates_nationalities: ['🇩🇪', '🇫🇷'],
      amenities: ['WiFi', 'AC', 'Bills included', 'Furnished', 'Washing machine'],
      contact_name: 'Sofia',
      contact_whatsapp: '+34612345678',
      contact_email: 'sofia.mueller@student.de',
      nationality: 'German',
      university: 'Ludwig Maximilian University Munich',
      gender_preference: 'any' as const,
      photos: [],
      status: 'active' as const,
      expires_at: d(60),
    },
    {
      type: 'room_available' as const,
      title: 'Cozy room near the beach — Malvarrosa',
      description: 'Perfect for beach lovers! Private room 5 minutes walk from Malvarrosa beach. The apartment has a lovely terrace where we have breakfast in the mornings. 1 Spanish flatmate — very chill and rarely home. Great location for Erasmus students who love the beach lifestyle.',
      price: 380,
      neighborhood: 'Malvarrosa',
      room_type: 'private_room' as const,
      available_from: d(3),
      available_until: d(150),
      flatmates_count: 1,
      flatmates_nationalities: ['🇪🇸'],
      amenities: ['WiFi', 'AC', 'Furnished', 'Balcony'],
      contact_name: 'Marco',
      contact_whatsapp: '+34623456789',
      contact_email: 'marco.rossi@univr.it',
      nationality: 'Italian',
      university: 'University of Verona',
      gender_preference: 'any' as const,
      photos: [],
      status: 'active' as const,
      expires_at: d(60),
    },
    {
      type: 'room_available' as const,
      title: 'Studio apartment — El Carmen city centre',
      description: 'Beautiful studio apartment in the historic El Carmen neighbourhood. Completely renovated, modern kitchen, very bright. Perfect for someone who wants their own space. Walking distance to all universities, nightlife and the best restaurants in Valencia.',
      price: 650,
      neighborhood: 'El Carmen',
      room_type: 'studio' as const,
      available_from: d(10),
      available_until: d(240),
      flatmates_count: 0,
      flatmates_nationalities: [],
      amenities: ['WiFi', 'AC', 'Bills included', 'Furnished', 'Private bathroom'],
      contact_name: 'Emma',
      contact_whatsapp: '+34634567890',
      contact_email: 'emma.dupont@univ-paris.fr',
      nationality: 'French',
      university: 'Sciences Po Paris',
      gender_preference: 'any' as const,
      photos: [],
      status: 'active' as const,
      expires_at: d(60),
    },
    {
      type: 'room_available' as const,
      title: 'Large room in Benimaclet — student area',
      description: 'Spacious room in Benimaclet, the student neighbourhood of Valencia. 3 international flatmates — great atmosphere and very social. Close to UPV and UV universities. Lots of cheap restaurants and bars nearby. Perfect Erasmus experience guaranteed!',
      price: 350,
      neighborhood: 'Benimaclet',
      room_type: 'private_room' as const,
      available_from: d(7),
      available_until: d(150),
      flatmates_count: 3,
      flatmates_nationalities: ['🇮🇹', '🇵🇱', '🇬🇷'],
      amenities: ['WiFi', 'Furnished', 'Washing machine'],
      contact_name: 'Lucas',
      contact_whatsapp: '+34645678901',
      contact_email: 'lucas.silva@uc.pt',
      nationality: 'Portuguese',
      university: 'University of Coimbra',
      gender_preference: 'any' as const,
      photos: [],
      status: 'active' as const,
      expires_at: d(60),
    },
    {
      type: 'room_available' as const,
      title: 'Room in shared flat — Mestalla near stadium',
      description: 'Nice room available in a quiet flat near Mestalla stadium. 2 Spanish flatmates, very respectful and clean. The flat has a great common area and a small balcony. Good transport connections to the city centre and universities.',
      price: 395,
      neighborhood: 'Mestalla',
      room_type: 'private_room' as const,
      available_from: d(14),
      available_until: d(180),
      flatmates_count: 2,
      flatmates_nationalities: ['🇪🇸', '🇪🇸'],
      amenities: ['WiFi', 'AC', 'Furnished', 'Balcony'],
      contact_name: 'Anna',
      contact_whatsapp: '+34656789012',
      contact_email: 'anna.kowalski@uw.edu.pl',
      nationality: 'Polish',
      university: 'University of Warsaw',
      gender_preference: 'female' as const,
      photos: [],
      status: 'active' as const,
      expires_at: d(60),
    },
    {
      type: 'looking_for_room' as const,
      title: 'Erasmus student looking for room — June',
      description: 'Hi! I am Jan from Czech Republic, studying Computer Science at UPV. Looking for a private room from June 1st for 5 months. Budget around €350-450/month including bills. I am clean, quiet and respect shared spaces. Non-smoker. Would love to live with other international students!',
      price: 400,
      neighborhood: 'Benimaclet',
      room_type: 'private_room' as const,
      available_from: d(5),
      available_until: d(150),
      flatmates_count: 0,
      flatmates_nationalities: [],
      amenities: ['WiFi', 'AC'],
      contact_name: 'Jan',
      contact_whatsapp: '+34667890123',
      contact_email: 'jan.novak@cvut.cz',
      nationality: 'Czech',
      university: 'Czech Technical University Prague',
      gender_preference: 'any' as const,
      photos: [],
      status: 'active' as const,
      expires_at: d(60),
    },
    {
      type: 'looking_for_room' as const,
      title: 'Greek student looking for room near UV',
      description: 'Hello! My name is Elena, I am from Athens studying Law at UV. Looking for a room from July 1st for the full academic year. Budget €380-500/month. I love cooking Mediterranean food and sharing meals with flatmates. Clean, friendly and social. Happy to live with mixed nationalities!',
      price: 440,
      neighborhood: 'Ruzafa',
      room_type: 'private_room' as const,
      available_from: d(25),
      available_until: d(330),
      flatmates_count: 0,
      flatmates_nationalities: [],
      amenities: ['WiFi', 'AC', 'Bills included'],
      contact_name: 'Elena',
      contact_whatsapp: '+34678901234',
      contact_email: 'elena.papadaki@uoa.gr',
      nationality: 'Greek',
      university: 'University of Athens',
      gender_preference: 'female' as const,
      photos: [],
      status: 'active' as const,
      expires_at: d(60),
    },
  ]

  // eslint-disable-next-line @typescript-eslint/no-explicit-any
  const { error: listingsError } = await supabase.from('housing_listings').insert(listings as any)
  if (listingsError) return NextResponse.json({ error: 'listings: ' + listingsError.message }, { status: 500 })

  // ── 2. Housing partners ───────────────────────────────────────

  const partners = [
    {
      name: 'Erasmus Rooms Valencia',
      contact_name: 'Javier Martínez',
      contact_email: 'javier@erasmusrooms.com',
      contact_phone: '+34963111222',
      whatsapp: '+34633333444',
      description: 'Premium student accommodation in Valencia. Fully furnished rooms and apartments for Erasmus students. All bills included. Best locations in the city.',
      status: 'active' as const,
    },
    {
      name: 'Valencia Student Housing',
      contact_name: 'Maria García',
      contact_email: 'maria@valenciastudenthouse.com',
      contact_phone: '+34963222333',
      whatsapp: '+34644444555',
      description: 'Affordable student rooms across Valencia. International student friendly. English speaking staff.',
      status: 'active' as const,
    },
  ]

  const { data: insertedPartners, error: partnersError } = await supabase
    .from('housing_partners')
    .insert(partners)
    .select('id, name')
  if (partnersError) return NextResponse.json({ error: 'partners: ' + partnersError.message }, { status: 500 })

  const partnerMap: Record<string, string> = {}
  for (const p of insertedPartners ?? []) partnerMap[p.name] = p.id

  // ── 3. Partner rooms ──────────────────────────────────────────

  const rooms = [
    {
      partner_name: 'Erasmus Rooms Valencia',
      title: 'Modern Studio — Benimaclet',
      description: 'Fully furnished studio apartment in Benimaclet, the most popular student area. Recently renovated with modern kitchen and new furniture. Perfect for Erasmus students wanting their own space. All bills included — no surprises!',
      neighborhood: 'Benimaclet',
      room_type: 'studio' as const,
      monthly_rent: 550,
      deposit_amount: 550,
      platform_fee: 50,
      available_from: d(15),
      bills_included: true,
      flatmates_count: 0,
      flatmates_nationalities: [],
      amenities: ['WiFi', 'AC', 'Bills included', 'Furnished', 'Washing machine', 'Private bathroom'],
      gender_preference: 'any' as const,
      featured: true,
    },
    {
      partner_name: 'Erasmus Rooms Valencia',
      title: 'Erasmus-Ready Room — Mestalla',
      description: 'Private room in a shared flat with 2 other international students. The flat is specifically set up for Erasmus students — international environment guaranteed. Very clean and modern. Close to Mestalla stadium and excellent transport links.',
      neighborhood: 'Mestalla',
      room_type: 'private_room' as const,
      monthly_rent: 360,
      deposit_amount: 360,
      platform_fee: 50,
      available_from: d(5),
      bills_included: true,
      flatmates_count: 2,
      flatmates_nationalities: ['🇮🇹', '🇩🇪'],
      amenities: ['WiFi', 'AC', 'Bills included', 'Furnished', 'Washing machine'],
      gender_preference: 'any' as const,
      featured: true,
    },
    {
      partner_name: 'Erasmus Rooms Valencia',
      title: 'Cosy Room in Ruzafa — Share',
      description: 'Private room in Ruzafa, the trendiest neighbourhood in Valencia! 3 international flatmates — amazing social atmosphere. Walking distance to the best restaurants, bars and coffee shops. Erasmus Life students get priority.',
      neighborhood: 'Ruzafa',
      room_type: 'private_room' as const,
      monthly_rent: 380,
      deposit_amount: 380,
      platform_fee: 50,
      available_from: d(10),
      bills_included: true,
      flatmates_count: 3,
      flatmates_nationalities: ['🇫🇷', '🇵🇹', '🇵🇱'],
      amenities: ['WiFi', 'AC', 'Furnished', 'Washing machine'],
      gender_preference: 'any' as const,
      featured: true,
    },
    {
      partner_name: 'Erasmus Rooms Valencia',
      title: 'Beach Flat — Malvarrosa',
      description: 'Incredible location — 3 minute walk to Malvarrosa beach! Shared apartment with 2 other students. Large terrace with partial sea views. Perfect for the summer semester. Fully furnished and equipped.',
      neighborhood: 'Malvarrosa',
      room_type: 'private_room' as const,
      monthly_rent: 450,
      deposit_amount: 450,
      platform_fee: 50,
      available_from: d(20),
      bills_included: false,
      flatmates_count: 2,
      flatmates_nationalities: ['🇩🇪', '🇬🇷'],
      amenities: ['WiFi', 'AC', 'Furnished', 'Balcony'],
      gender_preference: 'any' as const,
      featured: false,
    },
    {
      partner_name: 'Valencia Student Housing',
      title: 'Budget Room — El Carmen',
      description: 'Affordable private room in El Carmen, the historic heart of Valencia. Perfect location for students who want to be in the middle of everything. Shared kitchen and bathroom. All you need for a great Erasmus semester.',
      neighborhood: 'El Carmen',
      room_type: 'private_room' as const,
      monthly_rent: 320,
      deposit_amount: 320,
      platform_fee: 30,
      available_from: d(7),
      bills_included: false,
      flatmates_count: 3,
      flatmates_nationalities: ['🇪🇸', '🇫🇷', '🇮🇹'],
      amenities: ['WiFi', 'Furnished'],
      gender_preference: 'any' as const,
      featured: false,
    },
    {
      partner_name: 'Valencia Student Housing',
      title: 'Premium Room — City Centre',
      description: 'Large private room in a premium flat in the city centre. Modern building with elevator, new furniture throughout. 2 professional young flatmates — quiet and respectful environment. Perfect for students who want comfort.',
      neighborhood: 'El Carmen',
      room_type: 'private_room' as const,
      monthly_rent: 520,
      deposit_amount: 520,
      platform_fee: 30,
      available_from: d(3),
      bills_included: true,
      flatmates_count: 2,
      flatmates_nationalities: ['🇪🇸', '🇬🇧'],
      amenities: ['WiFi', 'AC', 'Bills included', 'Furnished', 'Private bathroom'],
      gender_preference: 'any' as const,
      featured: false,
    },
  ]

  for (const { partner_name, ...room } of rooms) {
    const partnerId = partnerMap[partner_name]
    if (!partnerId) continue
    const { error } = await supabase.from('partner_rooms').insert({
      ...room,
      partner_id: partnerId,
      photos: [],
      status: 'available' as const,
    })
    if (error) return NextResponse.json({ error: `room "${room.title}": ${error.message}` }, { status: 500 })
  }

  return NextResponse.json({
    ok: true,
    student_listings: listings.length,
    partners: partners.length,
    partner_rooms: rooms.length,
  })
}
