import { NextResponse } from 'next/server'
import { getAdminClient } from '@/lib/supabase/admin'

export const dynamic = 'force-dynamic'

export async function POST() {
  const supabase = getAdminClient()

  const sponsors = [
    {
      name:                    'Kapital Madrid',
      logo_url:                null,
      website_url:             'https://grupo-kapital.com',
      description:             '7-floor mega club in the heart of Madrid — the most iconic nightlife venue in the city. Each floor has a different music style from hip-hop to Latin to commercial. A must for any Madrid night out.',
      discount_text:           'Free entry on the guestlist',
      discount_code:           'NRE2025',
      redemption_instructions: 'Send your name + NRE2025 to our WhatsApp before 11pm on event night to be added to the Kapital guestlist.',
      category:                'nightlife' as const,
      is_featured:             true,
      members_only:            false,
      status:                  'active' as const,
      display_order:           1,
    },
    {
      name:                    'Fabrik Madrid',
      logo_url:                null,
      website_url:             'https://www.fabrikmusic.es',
      description:             'The biggest electronic music club in Spain — 10,000 capacity warehouse in Humanes with world-class DJs every weekend. The ultimate techno and house experience near Madrid.',
      discount_text:           '30% off tickets',
      discount_code:           'NREFABRIK',
      redemption_instructions: 'Use code NREFABRIK at checkout on fabrikmusic.es or show at the box office before midnight.',
      category:                'nightlife' as const,
      is_featured:             true,
      members_only:            false,
      status:                  'active' as const,
      display_order:           2,
    },
    {
      name:                    'Opium Madrid',
      logo_url:                null,
      website_url:             'https://opiummadrid.com',
      description:             'Premium club and restaurant on Paseo de la Castellana. Latin nights, R&B and commercial house. Known for its stunning interior and top-tier crowd.',
      discount_text:           'Guestlist access + welcome drink',
      discount_code:           'NREOPIUM',
      redemption_instructions: 'Message us on Instagram @notregularevents to be added to Opium guestlist with a free welcome drink.',
      category:                'nightlife' as const,
      is_featured:             true,
      members_only:            true,
      status:                  'active' as const,
      display_order:           3,
    },
    {
      name:                    'Honest Greens Madrid',
      logo_url:                null,
      website_url:             'https://honestgreens.com',
      description:             'Fast-casual healthy food chain with multiple locations across Madrid. Fresh salads, grain bowls and proteins with a Mediterranean twist. Perfect for pre-party fuel.',
      discount_text:           '15% off your order',
      discount_code:           'NRE15',
      redemption_instructions: 'Show code NRE15 at any Honest Greens Madrid cashier or enter it on the app.',
      category:                'food_drink' as const,
      is_featured:             true,
      members_only:            true,
      status:                  'active' as const,
      display_order:           4,
    },
    {
      name:                    'BlaBlaCar',
      logo_url:                'https://upload.wikimedia.org/wikipedia/commons/thumb/d/df/BlaBlaCar_logo.svg/2560px-BlaBlaCar_logo.svg.png',
      website_url:             'https://www.blablacar.es',
      description:             'Ridesharing platform to travel across Spain and Europe at a fraction of the cost. Perfect for getting to and from NRE events in other cities or weekend trips.',
      discount_text:           '€5 off your first ride',
      discount_code:           'NRERIDE',
      redemption_instructions: 'Enter code NRERIDE on the BlaBlaCar app when booking your first ride.',
      category:                'travel' as const,
      is_featured:             false,
      members_only:            false,
      status:                  'active' as const,
      display_order:           5,
    },
    {
      name:                    'Holmes Place Madrid',
      logo_url:                null,
      website_url:             'https://www.holmesplace.es/en/club-madrid',
      description:             'Premium gym chain with 8 locations across Madrid. World-class facilities, pools, spa and group classes. The best place to work out before a big night out.',
      discount_text:           '2 months free with annual membership',
      discount_code:           'NREHOLMES',
      redemption_instructions: 'Visit any Holmes Place Madrid reception and mention code NREHOLMES — student ID required.',
      category:                'fitness' as const,
      is_featured:             false,
      members_only:            true,
      status:                  'active' as const,
      display_order:           6,
    },
    {
      name:                    'Mercado de San Miguel',
      logo_url:                null,
      website_url:             'https://www.mercadodesanmiguel.es',
      description:             'Madrid\'s iconic covered market near Plaza Mayor with over 30 gourmet stalls. Pintxos, wine, fresh seafood and artisan products. The best pre-dinner spot in the city.',
      discount_text:           '1 free glass of wine with €10 spend',
      discount_code:           'NREMSM',
      redemption_instructions: 'Show code NREMSM on your phone at any wine stall inside the market.',
      category:                'food_drink' as const,
      is_featured:             false,
      members_only:            false,
      status:                  'active' as const,
      display_order:           7,
    },
    {
      name:                    'Renfe Cercanías',
      logo_url:                null,
      website_url:             'https://www.renfe.com/es/es/cercanias/cercanias-madrid',
      description:             'Madrid\'s commuter rail network connecting the city to surrounding towns and event venues. Essential for getting to Fabrik and other out-of-city venues safely at night.',
      discount_text:           '50% student discount on monthly pass',
      discount_code:           'NRERENFE',
      redemption_instructions: 'Visit any Renfe station with student ID and mention NRE partnership for the student rate.',
      category:                'travel' as const,
      is_featured:             false,
      members_only:            false,
      status:                  'active' as const,
      display_order:           8,
    },
    {
      name:                    'El Tigre Madrid',
      logo_url:                null,
      website_url:             null,
      description:             'Famous Madrid bar on Calle Infantas known for its massive free tapas with every drink. A legendary pre-party spot popular with students and tourists alike.',
      discount_text:           '2 drinks + tapas for €9',
      discount_code:           'NRE',
      redemption_instructions: 'Say "NRE" to the bartender at El Tigre, Calle Infantas 30, for the deal.',
      category:                'food_drink' as const,
      is_featured:             false,
      members_only:            false,
      status:                  'active' as const,
      display_order:           9,
    },
    {
      name:                    'Glovo Madrid',
      logo_url:                'https://upload.wikimedia.org/wikipedia/commons/thumb/5/5c/Glovo_logo.svg/2560px-Glovo_logo.svg.png',
      website_url:             'https://glovoapp.com/es/es/madrid',
      description:             'On-demand delivery app for food, groceries and anything else across Madrid. Get post-party food delivered in under 30 minutes.',
      discount_text:           '€8 off first 3 orders',
      discount_code:           'NREGLOVO',
      redemption_instructions: 'Enter code NREGLOVO at checkout on the Glovo app — valid for new users only.',
      category:                'food_drink' as const,
      is_featured:             false,
      members_only:            false,
      status:                  'active' as const,
      display_order:           10,
    },
  ]

  // eslint-disable-next-line @typescript-eslint/no-explicit-any
  const { error } = await supabase.from('sponsors').insert(sponsors as any)
  if (error) return NextResponse.json({ error: error.message }, { status: 500 })

  return NextResponse.json({ ok: true, inserted: sponsors.length })
}
