import { NextResponse } from 'next/server'
import { getAdminClient } from '@/lib/supabase/admin'

export const dynamic = 'force-dynamic'

export async function POST() {
  const supabase = getAdminClient()

  const sponsors = [
    {
      name:                    'Basic-Fit',
      logo_url:                'https://upload.wikimedia.org/wikipedia/commons/thumb/9/9a/Basic-Fit_logo.svg/2560px-Basic-Fit_logo.svg.png',
      website_url:             'https://www.basic-fit.com/es-es',
      description:             'Affordable gym chain with multiple locations across Valencia. Open 24/7 with state-of-the-art equipment and classes.',
      discount_text:           '1st month free',
      discount_code:           'ERASMUSLIFE',
      redemption_instructions: 'Show your Erasmus Life member card at any Basic-Fit Valencia reception.',
      category:                'fitness' as const,
      is_featured:             true,
      members_only:            true,
      status:                  'active' as const,
      display_order:           1,
    },
    {
      name:                    'Valencia Bikes',
      logo_url:                'https://www.valenciabikes.com/wp-content/uploads/2019/01/logo-valencia-bikes.png',
      website_url:             'https://www.valenciabikes.com',
      description:             'Bike rental and guided city tours. Best way to explore Valencia at your own pace. E-bikes available.',
      discount_text:           '15% off any rental',
      discount_code:           'ERASMUSLIFE15',
      redemption_instructions: 'Show code online or in store at Calle del Pintor Sorolla 1.',
      category:                'travel' as const,
      is_featured:             true,
      members_only:            true,
      status:                  'active' as const,
      display_order:           2,
    },
    {
      name:                    'Impact Hub Valencia',
      logo_url:                'https://impacthub.net/wp-content/uploads/2021/09/IH-logo-black.png',
      website_url:             'https://valencia.impacthub.net',
      description:             'Creative coworking space and startup community in the heart of Valencia. Events, networking and inspiration.',
      discount_text:           '3 free day passes',
      discount_code:           'ERASMUSLIFE',
      redemption_instructions: 'Show your digital member card at reception — C/ Grabador Esteve 4.',
      category:                'tech' as const,
      is_featured:             true,
      members_only:            true,
      status:                  'active' as const,
      display_order:           3,
    },
    {
      name:                    'Espit Chupitos',
      logo_url:                'https://espitchupitos.es/wp-content/uploads/2019/09/logo-espit.png',
      website_url:             'https://espitchupitos.es',
      description:             'The most famous shot bar in Valencia with over 500 different shots. A must-visit during your Erasmus!',
      discount_text:           '2 free shots',
      discount_code:           'ERASMUSLIFE',
      redemption_instructions: 'Show your digital member card at the bar — Calle Caballeros 41, El Carmen.',
      category:                'nightlife' as const,
      is_featured:             true,
      members_only:            true,
      status:                  'active' as const,
      display_order:           4,
    },
    {
      name:                    'FlixBus',
      logo_url:                'https://upload.wikimedia.org/wikipedia/commons/thumb/7/71/Flixbus_logo.svg/2560px-Flixbus_logo.svg.png',
      website_url:             'https://www.flixbus.es',
      description:             'Affordable bus travel across Spain and Europe. Perfect for Erasmus trips on a budget.',
      discount_text:           '10% off all bookings',
      discount_code:           'ERASMUSLIFE',
      redemption_instructions: 'Use code at checkout on flixbus.es or the FlixBus app.',
      category:                'travel' as const,
      is_featured:             true,
      members_only:            true,
      status:                  'active' as const,
      display_order:           5,
    },
    {
      name:                    'Decathlon Valencia',
      logo_url:                'https://upload.wikimedia.org/wikipedia/commons/thumb/3/31/Decathlon_logo.svg/2560px-Decathlon_logo.svg.png',
      website_url:             'https://www.decathlon.es/es/store/decathlon-valencia-avda-del-cid',
      description:             'Everything you need for sports and outdoor activities. Great prices for students. Multiple locations in Valencia.',
      discount_text:           '10% off purchase',
      discount_code:           'ERASMUSLIFE10',
      redemption_instructions: 'Show code at checkout online or in store at Avenida del Cid.',
      category:                'fitness' as const,
      is_featured:             false,
      members_only:            true,
      status:                  'active' as const,
      display_order:           6,
    },
    {
      name:                    'Papagayo Beach Club',
      logo_url:                'https://papagayo.es/wp-content/uploads/2020/01/logo-papagayo.png',
      website_url:             'https://papagayo.es',
      description:             'Trendy beach club on Malvarrosa beach. Sun beds, cocktails and DJ sessions every weekend.',
      discount_text:           'Free entry + welcome drink',
      discount_code:           'ERASMUSLIFE',
      redemption_instructions: 'Show member card at entrance — Paseo Marítimo, Malvarrosa Beach.',
      category:                'nightlife' as const,
      is_featured:             false,
      members_only:            true,
      status:                  'active' as const,
      display_order:           7,
    },
    {
      name:                    'Centre d\'Idiomes UV',
      logo_url:                'https://www.uv.es/uvweb/centre-idiomes/images/logo-centre-idiomes.png',
      website_url:             'https://www.uv.es/uvweb/centre-idiomes',
      description:             'Official Spanish and Valencian language courses for international students at the University of Valencia.',
      discount_text:           '25% off language courses',
      discount_code:           'ERASMUSLIFEUV',
      redemption_instructions: 'Mention code when enrolling at Centre d\'Idiomes, University of Valencia.',
      category:                'other' as const,
      is_featured:             false,
      members_only:            true,
      status:                  'active' as const,
      display_order:           8,
    },
    {
      name:                    'Biciclot',
      logo_url:                'https://biciclot.net/wp-content/uploads/2019/03/logo-biciclot.png',
      website_url:             'https://biciclot.net',
      description:             'Social bike cooperative in Valencia. Bike rental, repairs and cycling tours. Sustainable and affordable.',
      discount_text:           '20% off bike rental',
      discount_code:           'ERASMUSLIFEBC',
      redemption_instructions: 'Show member card at Biciclot — C/ de Enric Valor 11, Benimaclet.',
      category:                'travel' as const,
      is_featured:             false,
      members_only:            true,
      status:                  'active' as const,
      display_order:           9,
    },
    {
      name:                    'Nomad Coliving Valencia',
      logo_url:                null,
      website_url:             'https://nomadcolivingvalencia.com',
      description:             'Premium coliving space for international students and digital nomads in Ruzafa. Community events every week.',
      discount_text:           '1 week free trial',
      discount_code:           'ERASMUSLIFENC',
      redemption_instructions: 'Contact David at contact@nomadcolivingvlc.com with your member code.',
      category:                'other' as const,
      is_featured:             false,
      members_only:            true,
      status:                  'active' as const,
      display_order:           10,
    },
  ]

  // eslint-disable-next-line @typescript-eslint/no-explicit-any
  const { error } = await supabase.from('sponsors').insert(sponsors as any)
  if (error) return NextResponse.json({ error: error.message }, { status: 500 })

  return NextResponse.json({ ok: true, sponsors: sponsors.length })
}
